### PR TITLE
Resolve/completion for wrappers

### LINKED ISSUE #18: Snakemake wrappers resolve/completion
Resolve / completion from the configured wrappers repo

```
rule samtools_sort:
    input:
        "mapped/{sample}.bam"
    output:
        "mapped/{sample}.sorted.bam"
    params:
        "-m 4G"
    threads: 8
    wrapper:
        "0.0.8/bio/samtools_sort"
```

> Here, Snakemake will automatically downloads the corresponding wrapper from https://bitbucket.org/snakemake/snakemake-wrappers/src/0.0.8/bio/samtools_sort/wrapper.py.

> . Alternatively, e.g., for development, the wrapper directive can also point to full URLs, including URLs to local files with absolute paths file:// or relative paths file:. 

Update: Bitbucket wrappers deprecated (https://bitbucket.org/snakemake/snakemake-wrappers/src/62b507647dde?at=master) use GitHub repo (https://github.com/snakemake/snakemake-wrappers)

### PR DESCRIPTION
**Pull request by SimonTsirikov**
Fixes #18

### CODE REVIEW

**Comment by iromeo** [comment]
Autocompletion works after `0.36.0/bio` but not after `master/bio` or `latest/bio`
image 
image

Is it a bug? Bundled wrappers are 0.64.0, so I assume we try to show them in autocompletion for other version when we don't know the answer. So seems it should work for `master/bio` and for `latest/bio`

**Comment by iromeo** [comment]
Documentation popup doesn't work properly for `master/bio/multiqc`. E.g. link to external source code works, but link to documentation code doesn't work (404 error, `https://snakemake-wrappers.readthedocs.io/en/master/wrappers/multiqc.html` isn't correct here, should be `https://snakemake-wrappers.readthedocs.io/en/latest/wrappers/multiqc.html`)

**Comment by SimonTsirikov** [comment]
If user starts typing name of wrapper, bundled version is suggested.
Screenshot from 2020-08-31 13-34-15
But if user types version first and it matches regex `(\d+\.\d+\.\d+|master|latest).*`, this version is suggested instead of bundled one. 
Screenshot from 2020-08-31 13-35-03
Screenshot from 2020-08-31 13-35-26

**Comment by iromeo** [comment]
Changed wrappers root from bundled to my custom dir `/Users/romeo/PycharmProjects/snakecharm_tests/wrappers` but completion  shows old bundled information

image

image

**Comment by iromeo** [comment]
> If user starts typing name of wrapper, bundled version is suggested.
Ok, thx for fix

**Comment by iromeo** [comment]
Params parsing false positive: Wrapper sections detection false positive: 'shell' is missing #311

**Comment by iromeo** [comment]
Also see https://github.com/JetBrains-Research/snakecharm/issues/312

**Pull request merged**
